name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on:
      - self-hosted
      - linux
      - x64
      - terraform-provider-phala
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Checkout Go SDK (for replace directive ../go)
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          repository: Phala-Network/phala-cloud
          ref: main
          path: phala-cloud
          sparse-checkout: go
          sparse-checkout-cone-mode: true
      - run: rm -rf ../go && mv phala-cloud/go ../go && rm -rf phala-cloud
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85
        with:
          terraform_wrapper: false
      - run: make generate
      - name: Check generated docs
        run: git diff --exit-code
      - run: make ci
